name: Run RSS Feed Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python sec-news.py  # Replace with your actual script name

      - name: Commit changes
        run: |
          git config --local user.email "your_email@example.com"  # Replace with your email
          git config --local user.name "GitHub Actions"  # You can name it anything
          git add sec-news.md  # Add the output file (replace with your actual output file)
          git commit -m "Update articles published on $(date '+%Y-%m-%d')" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main  # Push changes to the main branch (adjust if your default branch is different)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides a token for authentication
