name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python sec-news.py  # Replace with your script name

      - name: Commit changes
        run: |
          git config --local user.email "darpankatarya@gmail.com"
          git config --local user.name "GitHub Actions"
          git add README.md  # Add the output file
          git commit -m "Update articles published on $(date '+%Y-%m-%d')" || echo "No changes to commit" || true

      - name: Push changes
        run: |
          git remote set-url origin https://<your_github_username>:${{ secrets.MY_PAT }}@github.com/darpan-97/sec-news.git
          git push origin main
